async (page) => {
  const passed = [];
  const assert = (value, message) => { if (!value) throw Error(message); };
  const primary = page.locator('.primary');
  await page.evaluate(() => { window.__mock.reject = true; });
  await primary.click();
  await page.getByText('Request cancelled. Try again when ready.').waitFor();
  assert(await primary.isEnabled(), 'Rejected connection must be retryable');
  passed.push('rejected connection recovers');
  await page.evaluate(() => { window.__mock.reject = false; });
  await primary.click();
  await page.getByRole('button', { name: 'Switch to Sepolia', exact: true }).waitFor();
  await primary.click();
  await page.waitForFunction(() => document.querySelector('.primary').textContent.includes('Vote') && !document.querySelector('.primary').disabled);
  assert(await page.evaluate(() => window.__mock.calls.includes('wallet_addEthereumChain')), 'Missing add-chain fallback');
  passed.push('connect, add Sepolia, switch chain');
  for (const value of ['0', '-1', '1e-3', 'abc', '0.0000000000000000001', '']) {
    await page.locator('#amount').fill(value);
    await primary.click();
    assert(await page.locator('#amount').getAttribute('aria-invalid') === 'true', 'Accepted invalid amount ' + value);
    assert(await page.evaluate(() => document.activeElement.id) === 'amount', 'Invalid amount not focused');
  }
  assert(await page.evaluate(() => window.__mock.sent.length) === 0, 'Invalid amount sent');
  passed.push('six invalid amounts blocked and focused');
  await page.getByRole('button', { name: '0.005', exact: true }).click();
  assert(await page.locator('#amount').inputValue() === '0.005', 'Preset failed');
  await page.evaluate(() => { window.__mock.reject = true; });
  await primary.click();
  await page.getByText('Request cancelled. Try again when ready.').waitFor();
  passed.push('preset and rejected signature recover');
  await page.evaluate(() => { window.__mock.reject = false; window.__mock.balance = '0x0'; });
  await primary.click();
  await page.getByText('Not enough Sepolia ETH for the vote and gas.').waitFor();
  assert(await page.evaluate(() => window.__mock.sent.length) === 0, 'Insufficient funds sent');
  passed.push('insufficient balance blocked');
  await page.evaluate(() => { window.__mock.balance = '0x8ac7230489e80000'; window.__mock.badCode = true; });
  await primary.click();
  await page.getByText('Contract verification failed. Reconnect to Sepolia and retry.').waitFor();
  assert(await page.evaluate(() => window.__mock.sent.length) === 0, 'Unverified contract sent');
  passed.push('runtime mismatch blocked');
  await page.evaluate(() => { window.__mock.badCode = false; });
  await primary.click();
  await page.getByText('Waiting for confirmation.').waitFor();
  const transaction = await page.evaluate(() => window.__mock.sent[0]);
  assert(transaction.to.toLowerCase() === await page.evaluate(() => window.__mock.address), 'Wrong recipient');
  assert(transaction.from === await page.evaluate(() => window.__mock.first), 'Wrong sender');
  assert(transaction.data === await page.evaluate(() => window.__mock.selectors.vote), 'Wrong calldata');
  assert(BigInt(transaction.value) === 5000000000000000n, 'Wrong value');
  assert(await primary.isDisabled(), 'Pending button enabled');
  await page.locator('form').evaluate(form => form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })));
  assert(await page.evaluate(() => window.__mock.sent.length) === 1, 'Duplicate submission');
  passed.push('exact recipient, sender, selector, 0.005 ETH; duplicate blocked');
  await page.reload();
  await page.getByText('Waiting for confirmation.').waitFor();
  assert(await primary.isDisabled(), 'Reload lost pending guard');
  passed.push('pending hash survives reload');
  await page.evaluate(() => { window.__mock.receipt = '0x1'; window.__mock.votes = '13'; window.__mock.received = '65000000000000000'; window.__mock.amounts[0] = '35000000000000000'; });
  await page.getByText('Vote confirmed.', { exact: false }).waitFor();
  await page.waitForFunction(() => document.querySelector('.totals dd').textContent === '13');
  passed.push('confirmed receipt refreshes counts and board');
  return { passed, transaction };
}
